### ISSUE TITLE
TypeError: Cannot set property 'innerHTML' of null

### ISSUE THREAD

**Issue by Guruleenyc** [Organizr/docker-organizr#10]
I am seeing this intermittently. The iframe refresh does not resolve it, but a full browser page refresh resolves it. I am using Brave browser with shields off the site.
`TypeError: Cannot set property 'innerHTML' of null
response:

result: success

message:

data:

data:

x.x.x.x:

domains_being_blocked: 919584

dns_queries_today: 82145

ads_blocked_today: 7831

ads_percentage_today: 9.533143

unique_domains: 7305

queries_forwarded: 40695

queries_cached: 33483

clients_ever_seen: 41

unique_clients: 34

dns_queries_all_types: 82145

reply_NODATA: 6823

reply_NXDOMAIN: 9322

reply_CNAME: 10675

reply_IP: 41582

privacy_level: 0

status: enabled

gravity_last_updated:

file_exists: true

absolute: 1604809589

relative:

days: 2

hours: 10

minutes: 36

options:

combine: false

title: true`

**Comment by christronyxyocum** [comment]
Ok.....  We're going to need more information than this. Where are you seeing this? Are there any errors in the browser console, the Nginx log, the Organizr log, etc? Have you tried another browser? Possibly with private/incognito mode? Have you tried another machine/device entirely?

**Comment by christronyxyocum** [comment]
Closing as this seems to be an issue with the Organizr software and an issue should be opened in the correct repo: https://github.com/causefx/Organizr
