### ISSUE TITLE
Mapped storage Docker best practice?

### ISSUE THREAD

**Issue by jhelmink** [Organizr/docker-organizr#12]
Shouldn't the mapped `/config` path basically only contain the db and config files?
It seems to me as if the entire application is stored in the config folder.
I thought the Docker Container should contain all the application data, and then when a new version is released, the container is updated, and inherits the existing config data. With the current set up that wouldn't be possible I don't think?

**Comment by christronyxyocum** [comment]
There are too many possible customizations that users can to do various things within Organizr so it's better to have it all mapped. The application is not stored within the Docker image, it is managed via git and kept in the /config directory.

**Comment by Roxedus** [comment]
Due to the nature of how organizr stores it's data, it wouldn't be feasible to achieve this. We need to account for the config file (which currently has to be in the project folder), uploaded images and other files that are scattered around.
