### ISSUE TITLE
Arm64 image not working on RPI 4: standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by telefax** [Organizr/docker-organizr#13]
I'm running docker on centos inside a vmware vm on RPI 4.

I tried docker run with all arm tags but they just result in:

`standard_init_linux.go:211: exec user process caused "exec format error"`

When I ran docker build on linux-arm64.Dockerfile, then the container starts!

The image inspect arch says: 
"Architecture": "arm64" which is the same as organizr/organizr:arm64.

```
uname -a
Linux cs001 4.18.0-193.28.1.el8_2.aarch64 #1 SMP Thu Oct 22 00:42:58 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by Roxedus** [comment]
Do you have any multiarch images running?

**Comment by telefax** [comment]
I guess so, I'm running:

traefik:latest
influxdb
jacobalberty/unifi:latest
grafana/grafana

**Comment by telefax** [comment]
Now I'm trying to figure out why there are no files in /config/www/organizr, guess I missing something here.

**Comment by Roxedus** [comment]
Does the `linux-arm64` tag work?

**Comment by telefax** [comment]
> `linux-arm64`

Nope :(
```

# docker container run organizr/organizr:linux-arm64

standard_init_linux.go:211: exec user process caused "exec format error"
```

```
# docker container run organizr/organizr:latest
standard_init_linux.go:211: exec user process caused "exec format error"
```

Trying on an RPI 3 running raspian and it works.

I spotted something now, in the RPI 3 the scripts are executable (+x) but not on RPI 4:

```
root@49cab85d24d5:/etc/cont-init.d$ ls -ltr
total 24
-rw-r--r-- 1 root root  190 Oct 23 20:03 50-debug
-rw-r--r-- 1 root root 2241 Oct 23 20:03 30-setup
-rw-r--r-- 1 root root 1484 Oct 23 20:03 20-config
-rw-r--r-- 1 root root  350 Oct 23 20:03 10-adduser
-rw-rw-rw- 1 root root 3410 Oct 29 21:27 40-install
-rw-rw-rw- 1 root root 1394 Oct 29 21:27 35-fpm

```

I think this is whats causing the trouble.

**Comment by telefax** [comment]
Ok, so I poked around a little (+x was not the issues) and now it seems that the official images I pulled has s6 in 32bit + wrong arch , which fails on the RPI 4.

For instance: 
Using organizr/organizr:latest which gives format error:
```
file /bin/importas
/bin/importas: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
```

Using docker-compose with docker-base and create an image, where this file executes fine.

```
file /bin/importas
/bin/importas: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped

```

So I used docker-compose to build docker-organizr as well, based on my own docker-base image and it now has the correct s6 binaries and the /init script runs fine.

So, back on my RPI 3:

```
file /bin/importas
/bin/importas: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
```

So, Is his simply a cross compilation issues where arm64 is not really arm64?

**Comment by Roxedus** [comment]
Good catch. I will modify the buildprocess to pull explicit arches, rather than relying on the manifest.

**Comment by Roxedus** [comment]
I did some changes to explicit do the arches, can you try `roxedus/organizr`?

**Comment by telefax** [comment]
Yepp, works perfect now!  :)

**Comment by Roxedus** [comment]
Awesome, will merge now, and you can go back to the official one pretty soon
