### ISSUE TITLE
Could not resolve host github.com

### ISSUE THREAD

**Issue by xam2828** [Organizr/docker-organizr#17]
Hello,

First of all, thank you for your great work.

I'm currently having an issue with my organizr installation. A little background : 

A few months ago,  I reinstalled all my services on a brand new raspberry pi 4, running on DietPi. I used the DietPi menu to easily install docker, and then a container for each service, including Organizr. Everything was working fine, and I documented the steps.

A few weeks ago, I decided to move all my front services onto another raspberry pi 3 that I had lying around, to lighten the workload on each hardware. I did the exact same things : 

- Install DietPi
- Install Samba and mount my drives
- Install Docker through the helper
- Install my containers with the code I used on my previous install, which was working perfectly

I am having a weird issue with my organizr installation. It says that it could not resolve github.com and therefore could not proceed with the installation. Find below the logs when I start the container attached.

> usermod: no changes
> 
> -------------------------------------
> GID/UID
> -------------------------------------
> User uid:    1000
> User gid:    1000
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 20-config: executing...
> [cont-init.d] 20-config: exited 0.
> [cont-init.d] 30-setup: executing...
> [cont-init.d] 30-setup: exited 0.
> [cont-init.d] 40-install: executing...
> -----------------------
> | Installing Organizr |
> -----------------------
> Cloning into '/config/www/organizr'...
> fatal: unable to access 'https://github.com/causefx/Organizr/': Could not resolve host: github.com
> [cont-init.d] 40-install: exited 1.
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.
> [s6-finish] sending all processes the KILL signal and exiting.

The folder ownership is correctly configured : 
![image](https://user-images.githubusercontent.com/77001242/108479631-40a2bd00-7296-11eb-9573-784280acbc58.png)

The user is correctly configured : 
![image](https://user-images.githubusercontent.com/77001242/108479694-531cf680-7296-11eb-8513-865a55a5e25b.png)

Here's the code I'm using to install the image and run the container : 
`docker run -d --restart unless-stopped \
--name=organizr \
-v /media/config/organizr:/config \
-e PGID=1000 -e PUID=1000  \
-p 80:80 \
organizr/organizr`

This is the exact same code I used from the previous install. Also, I tried running it again on the first Pi I was using and the same error shows up.

I can correctly ping github.com from the host : 
![image](https://user-images.githubusercontent.com/77001242/108479942-a000cd00-7296-11eb-8538-61deb37f2596.png)

I can correctly ping github.com from another container : 
![image](https://user-images.githubusercontent.com/77001242/108480053-c1fa4f80-7296-11eb-8a70-5409702353b2.png)

I can't show you if I can ping github.com from the organizr container since it won't start because of the issue.

Here's my docker version : 
![image](https://user-images.githubusercontent.com/77001242/108480180-e9511c80-7296-11eb-9713-a089c37fa51b.png)

Do you see any issues with my setup ? Any workaround I could use ?

I'm fairly new to Docker and I need help cause I fail to comprehend what I'm doing wrong.

Thanks a lot

**Comment by Roxedus** [comment]
You are running into this https://docs.linuxserver.io/faq#libseccomp

**Comment by xam2828** [comment]
Wow man, I have not idea how you pinpointed to this, but it instantly fixed it.

Truly impressed. Thanks for the support.
