### ISSUE TITLE
Support versioned docker containers

### ISSUE THREAD

**Issue by Ornias1993** [Organizr/docker-organizr#18]
Some of us supply Helm charts to role out Organizr to other users.
It's best practice to bind a specific version of the underlaying app or container, to a specific version of the chart. This makes sure the chart is thoroughly tested with said specific version of the App/Container.

It would be nice if you guys could push some versioned containers, either together with Organizr updates or seperate versions based on the container (for example: v2.*incremental number*)

**Comment by Roxedus** [comment]
We would if there was any sane way to do it. The app does not live in the container, so its not something we can do. The way organizr currently does its storage prevents us from having the app in the image.

**Comment by Ornias1993** [comment]
Ahh understandable, in that case the chance of anything breaking based on just changes in the container itself (and not the app) is indeed very small and not worth versioning for.

Thanks for taking the time to write down an explaination though :)
