### ISSUE TITLE
default will be overwritten every startup

### ISSUE THREAD

**Issue by DunklerPhoenix** [Organizr/docker-organizr#2]
heho
I have an services.conf file which configures nginx as reverse proxy for my services.
I'm adding it with `include /config/nginx/services.conf;` to the default file, but with the latest image (27.08.2020 23:50 [+2 MESZ]) the default file will be overwritten on every startup.

Image: https://hub.docker.com/layers/organizr/organizr/latest/images/sha256-eaa184dc475056312ae5a2d9a51cf4acf326023bcc0b21d4e1ed9c9b773cacb7?context=explore

Do you have any advice how to fix it?
Greetings

**Comment by Roxedus** [comment]
Can you add a comment in your deployment file?
