### ISSUE TITLE
Latest update drives nginx 403 error

### ISSUE THREAD

**Issue by nationapn** [Organizr/docker-organizr#24]
Using "organizr/organizr:latest" UnRAID Docker image, organizr displays an nginx 403 error.

My log file:
ErrorWarningSystemArrayLogin

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
GID/UID
-------------------------------------
User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing...
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 40-install: executing...
-----------------------
| Updating Organizr |
-----------------------
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sed: /config/www/organizr/api/config/config.php: No such file or directory
sed: /config/www/organizr/api/config/default.php: No such file or directory
Adding cron now...
[cont-init.d] 40-install: exited 0.
[cont-init.d] 50-debug: executing...
-----------------------
| Kernel Info |
-----------------------
Linux 5cc4669f9963 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64 GNU/Linux
Time Zone: America/New_York
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...

appreciate any help/assistance.  Organizr was working reliably for months until this recent update.

**Comment by HalianElf** [comment]
Seems like something went screwy with your `/config` and possibly more considering the `ErrorWarningSystemArrayLogin` is from Unraid and not from the container. How did you have your `/config` mapped?

**Comment by nationapn** [comment]
Hmm, I thought my config was pretty standard…

![008E34CD-3E89-4C09-A24E-893AF1A6D7F1](https://user-images.githubusercontent.com/69475806/143496654-96b7a6d3-43b8-47f7-bcfa-4ca8f546d6dd.jpeg)

**Comment by HalianElf** [comment]
Yea, that looks normal... May want to look into your Unraid logs too since that first log message seems like you got a bigger issue with your server.

**Comment by nationapn** [comment]
I think the UnRAID error was unrelated...everything else on my server is running normally...I restarted the system and no longer get the UNRAID error.  New organizr log:


[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
GID/UID
-------------------------------------
User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing...
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 40-install: executing...
-----------------------
| Updating Organizr |
-----------------------
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sed: /config/www/organizr/api/config/config.php: No such file or directory
sed: /config/www/organizr/api/config/default.php: No such file or directory
Adding cron now...
[cont-init.d] 40-install: exited 0.
[cont-init.d] 50-debug: executing...
-----------------------
| Kernel Info |
-----------------------
Linux 5cc4669f9963 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64 GNU/Linux
Time Zone: America/New_York
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
No cron file to run...
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes

-------------------------------------
GID/UID
-------------------------------------
User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-setup: executing...
[cont-init.d] 30-setup: exited 0.
[cont-init.d] 40-install: executing...
-----------------------
| Updating Organizr |
-----------------------
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sed: /config/www/organizr/api/config/config.php: No such file or directory
sed: /config/www/organizr/api/config/default.php: No such file or directory
Cron already added...
[cont-init.d] 40-install: exited 0.
[cont-init.d] 50-debug: executing...
-----------------------
| Kernel Info |
-----------------------
Linux 5cc4669f9963 5.10.28-Unraid #1 SMP Wed Apr 7 08:23:18 PDT 2021 x86_64 GNU/Linux
Time Zone: America/New_York
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
No cron file to run...
No cron file to run...
No cron file to run..

**Comment by causefx** [comment]
what is inside /mnt/user/appdata/organizr

**Comment by nationapn** [comment]
the typical directories...keys, log, nginx, php, and www.  Reading into the log, I'm not sure what drives this error:

"fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary"

However, looking in the /www/organizr/api/config/ directory, the only file there was a config.bak.php file.

My best guess is that something became corrupt or failed on the last update.  Unfortunately, unless someone with a bit more knowledge than me has an idea to rectify, I think I'll just have to install a fresh docker image and reconfigure from scratch.

Sounds like this is very likely an issue just for me (not an issue with the latest update) but I wanted to post here just in case others had the same issue.

Thanks so far for the comments/help, and for those in the US, Happy Thanksgiving :)

**Comment by HalianElf** [comment]
Check and see if you have a backup in your www/db folder. If you do, just blow away the whole appdata directory for organizr, let it recreate and then restore the backup back and you should be back to normal. Only thing you may end up missing is any custom tab images you may have uploaded.

**Comment by nationapn** [comment]
@HalianElf - thank you so much!  That did the trick!!  I’m back up and running now 🙂🙌🏻
