### ISSUE TITLE
Unable to load NPM/Pi-Hole/PHPMyAdmin/QBitTorrent in iFrame

### ISSUE THREAD

**Issue by Trolann** [Organizr/docker-organizr#27]
Through troubleshooting I've found my issue is related to X-Frame-Options header. I've gotten QBitTorrent working by changing some internal security settings, but I can't get the rest to show. I get 'subdomain.domain.tld refused to connect' with local or external addresses.

In the proxy host configs I've tried adding this header from sameorigin, named origin/domains and hiding the header entirely to no effect. Loading these in new windows works. I did not see anything referenced in the nginx configs repo.

**Comment by Roxedus** [comment]
This is not a container issue, neither a Organizr issue. Join the discord for support.

**Comment by Trolann** [comment]
For those googling in the future: if you run into this Organizr doesn't support this configuration in an iFrame. The users on discord will give you the same header information above but can't get it to work.

**Comment by HalianElf** [comment]
If by doesn't support this configuration you mean you can't have mixed content, sure. The issue you had (from the discord conversation) had nothing to do with headers. Your issue from the screenshots was solely due to not having the tab proxied so it too was HTTPS.
