### ISSUE TITLE
healthscript broken

### ISSUE THREAD

**Issue by DunklerPhoenix** [Organizr/docker-organizr#3]
heho.
Since the new image from 27.08.2020 23:50 [+2 MESZ] the healthscript doesn't work anymore:
`curl: (22) The requested URL returned error: 404 Not Found curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
--`

Image: https://hub.docker.com/layers/organizr/organizr/latest/images/sha256-eaa184dc475056312ae5a2d9a51cf4acf326023bcc0b21d4e1ed9c9b773cacb7?context=explore

**Comment by Roxedus** [comment]
I have only seen this when the healthcheck is defined outside of the container, ie in compose. Portainer also doesn't update the healthcheck if you just replace image.

**Comment by Roxedus** [comment]
Keep in mind that the healthcheck also depends on the stock nginx setup

**Comment by DunklerPhoenix** [comment]
Ah I see. It works again for me 👍 

Wouldn't it be better to move this into a script?
In my images I create the healthcheck like this to easy edit it without breaking anything.
`HEALTHCHECK &{["CMD-SHELL" "/opt/bot/health.sh"] "20s" "15s" "15s" '\x03'}`
(In newer Images I'll move the times also into the script.)

**Comment by Roxedus** [comment]
No. This is why docker allows you to define the healthchecks yourself
