### ISSUE TITLE
Unable to bind to a unique port in docker compose network

### ISSUE THREAD

**Issue by MulverineX** [Organizr/docker-organizr#32]
I would like to use port `4602` for organizr, but unfortunately, with the way my docker compose file is setup, I cannot use `ports:`. Could you please add support for a `port` environment variable to change it from `80`?

**Comment by qdm12** [comment]
That's not an edge case and really something very basic, having the internal listening port configurable is critical in a few cases. Also port `80` forces you to run as root since it's below 1024, which not always desirable.
