### ISSUE TITLE
The image isn't updating

### ISSUE THREAD

**Issue by nuentes** [Organizr/docker-organizr#33]
The image I keep pulling was created on 5/8/2022. I have branch set to v2-master. I can see this branch has updated very recently on https://github.com/causefx/Organizr. I keep getting alerts that Organizr has updates.

**Comment by Roxedus** [comment]
The image does not need to be updated to get the latest commits, restart the container, or use the built-in updater.

**Comment by nuentes** [comment]
I've restarted the container at least 6 times today already. I also restarted my entire server. I have also tried to update using the built in updater (settings -> system settings -> Updates -> install update). This appears as though it is working each time, however when the page refreshes, I am immediately greeted with a note that it is out of date.

Every other container I use, the image itself updates when there are new commits.

**Comment by Roxedus** [comment]
And the container logs say?

**Comment by Roxedus** [comment]
Remove the lockfile it mentions,

**Comment by nuentes** [comment]
Well, I had nothing to do with that file being there. But removing that file resolved the issue. Thank you
