### ISSUE TITLE
fatal: detected dubious ownership in repository at '/config/www/organizr' error

### ISSUE THREAD

**Issue by CyberFreek** [Organizr/docker-organizr#35]
Hi, 

I am getting the following error when I try to start organizr:

`
|  Updating Organizr  |

fatal: detected dubious ownership in repository at '/config/www/organizr'
To add an exception for this directory, call:
	git config --global --add safe.directory /config/www/organizr
fatal: detected dubious ownership in repository at '/config/www/organizr'
To add an exception for this directory, call:
	git config --global --add safe.directory /config/www/organizr
fatal: detected dubious ownership in repository at '/config/www/organizr'
To add an exception for this directory, call:
	git config --global --add safe.directory /config/www/organizr
fatal: detected dubious ownership in repository at '/config/www/organizr'
To add an exception for this directory, call:
	git config --global --add safe.directory /config/www/organizr
fatal: detected dubious ownership in repository at '/config/www/organizr'
To add an exception for this directory, call:
	git config --global --add safe.directory /config/www/organizr
fatal: detected dubious ownership in repository at '/config/www/organizr'
To add an exception for this directory, call:
	git config --global --add safe.directory /config/www/organizr
Adding cron now...
[cont-init.d] 40-install: exited 0.
[cont-init.d] 50-debug: executing... 

|     Kernel Info     |

Linux f6a666ca75b4 5.15.123.1-microsoft-standard-WSL2 #1 SMP Mon Aug 7 19:01:48 UTC 2023 x86_64 GNU/Linux
Time Zone: PST8PDT
[cont-init.d] 50-debug: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int - string in
//
/config/www/organizr/api/functions/normal-functions.php:525
Stack trace:
#0 /config/www/organizr/api/functions/normal-functions.php(579): Organizr->convertIPToRange()
#1 /config/www/organizr/api/functions/normal-functions.php(611): Organizr->localIPRanges()
#2 /config/www/organizr/api/functions/normal-functions.php(625): Organizr->isLocal()
#3 /config/www/organizr/cron.php(4): Organizr->isLocalOrServer()
`

The output of
 `docker inspect -f '{{ index .Config.Labels "org.opencontainers.image.created"}}' $(docker image ls ghcr.io/organizr/organizr -q)`  is:
2023-11-30_13

And my docker compose is:
`    
organizr:
        image: ghcr.io/organizr/organizr:latest
        labels:
          - "com.centurylinklabs.watchtower.enable=true"
        container_name: organizr
        environment:
            - fpm=true
            - branch=v2-master
            - PUID=${PUID} # default user id, defined in .env
            - PGID=${PGID} # default group id, defined in .env
            - TZ=${TZ} # timezone, defined in .env
            - UMASK=${UMASK} #  ensure that files and folders created by one can be read and written by the others.
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${CONFIGS}/organizr:/config #a config files
        restart: unless-stopped
        ports:
            - "80:80"
        `

**Comment by Roxedus** [comment]
Should be good now

**Comment by CyberFreek** [comment]
Hi,

The permission error seems resolved but the other error is still there:

`  thrown in /config/www/organizr/api/functions/normal-functions.php on line 525
}
PHP Fatal error:  Uncaught TypeError: Unsupported operand types: int - string in /config/www/organizr/api/functions/normal-functions.php:525

Stack trace:
#0 /config/www/organizr/api/functions/normal-functions.php(579): Organizr->convertIPToRange()
#1 /config/www/organizr/api/functions/normal-functions.php(611): Organizr->localIPRanges()
#2 /config/www/organizr/api/functions/normal-functions.php(625): Organizr->isLocal()
#3 /config/www/organizr/cron.php(4): Organizr->isLocalOrServer()`

Any thoughts on that one

**Comment by HalianElf** [comment]
That looks more like you have a busted config and one of your `localIP` variables in the config.php is not an IP. Has nothing to do with the container itself now.
