### ISSUE TITLE
Docker container loses access repeatedly to cron.php

### ISSUE THREAD

**Issue by Liziloo** [Organizr/docker-organizr#36]
Organizr docker works for up to a day, then opening the site gets a 404 error. Logs show:

Could not open input file: /config/www/organizr/cron.php

Changing permissions on the file does nothing. If I reinstall organizr, it works again for 12-24 hours, then the same error, despite no changes being made by me.

**Comment by Roxedus** [comment]
Post your compose/run

**Comment by Liziloo** [comment]
Problem corrected with a total reinstall of docker.
