### ISSUE TITLE
APIv1 works, but APIv2 gives "file not found"

### ISSUE THREAD

**Issue by DunklerPhoenix** [Organizr/docker-organizr#4]
Heho
If I use `/api/v2/auth?group=998` I get `File not found.`
`/api/?v1/auth&group=998` instead works without problems.

I resetted the whole nginx configuration of the docker container. (deleting nginx folder in config and then restart) 
So none of my services are included in the config.

Docker Tag: organizr/organizr:latest
Branch ENV: v2-master
Organizr Version: 2.0.650

Is v2 not supported at the moment or did I something wrong?

EDIT: 
I deleted also the www folder to reset organizr completely, but inside the www/organizr/api folder is no v2 folder.
It seems to be needed through:
```
location /api/v2 {
	try_files $uri /api/v2/index.php$is_args$args;
}
```
Even in repo https://github.com/causefx/Organizr/tree/v2-master/api is no v2 folder. Is this nginx config wrong?

Greetings

**Comment by gilbN** [comment]
Hi. Have a look at: https://docs.organizr.app/books/setup-features/page/organizr-20--%3E-21-migration-guide

**Comment by DunklerPhoenix** [comment]
I know this page already.
I found ot out now.
The v2-master branch does not include the api v2
I switched to v2-develop and it works.
Should be noted somewhere

**Comment by Roxedus** [comment]
It does mention organizr 2.1, which currently only is in the dev branch.

**Comment by mishac** [comment]
It's not clear that 2.1 is only in the dev branch.  Having version numbers for an unreleased branch seems confusing.
