### ISSUE TITLE
Custom favicon doesn't show up

### ISSUE THREAD

**Issue by RoryNesbitt** [Organizr/docker-organizr#5]
I followed the instructions for creating and adding a custom favicon to Organizr, however it doesn't show up but does remove the default one.
I added the files to the faviconCustom directory that contained addFaviconsHere.txt so I know that it's the correct location, and I copied and pasted the code from https://realfavicongenerator.net as plain text, so I'm all out of ideas

**Comment by Roxedus** [comment]
This is not a container issue, I just redid my favicon with the instructions with success.

**Comment by RoryNesbitt** [comment]
Good to know, a bit more screwing around and it seems to have decided to work.
Thanks for the quick reply
