### ISSUE TITLE
Migration issues from v2

### ISSUE THREAD

**Issue by jds11111** [Organizr/docker-organizr#6]
Against all advice, I have been using watchtower, because I set everything up by cli, before there was docker-compose. Today, of all days, when i am having nothing but computer problems, organizr stopped working because of the update. I got the 404 error that pointed me to a page on migration. It seemed that now was the time to migrate to yaml, too, since that is how the instructions started. I used red5s tool to generate a yaml from my current setup, and tried to edit it to fit the new instructions. I eventually got the following, which showed no errors:

> services:
>   organizr:
>     container_name: organizr
>     entrypoint:
>       - /init
>     environment:
>       - fpm=true
>       - branch=v2-master
>       - TZ=America/Chicago
>       - PGID=1000
>       - PUID=1000
>       - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
>       - HOME=/root
>       - TERM=xterm
>     hostname: organizr
>     image: organizr/organizr
>     ipc: private
>     logging:
>       driver: json-file
>       options: {}
>     mac_address: 02:42:ac:11:00:04
>     networks:
>       bridge:
>         aliases:
>          - organizr
>       htpc_network:
>         aliases:
>           - organizr
>           - 95ea9d19d1c8
>     ports:
>       - 80:80
>     restart: unless-stopped
>     volumes:
>       - /home/jds/configs/organizr/config:/config
> version: "3"
> networks:
>   bridge:
>     external: true
>   htpc_network:
>     external: true

However, this timesout getting the container:

```
$ docker-compose pull && docker-compose up -d
Pulling organizr ... error
ERROR: for organizr  Get https://registry-1.docker.io/v2/organizr/organizr/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Aorganizr%2Forganizr%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
ERROR: Get https://registry-1.docker.io/v2/organizr/organizr/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Aorganizr%2Forganizr%3Apull&service=registry.docker.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

**Comment by christronyxyocum** [comment]
I can pull the image fine so it must be something with your Internet connection or between your ISP and Docker Hub:

https://sharex.tronflix.app/zORI8/VuhUsiGo93.gif

**Comment by jds11111** [comment]
If I try a wget for the same, I get a username/password complaint. How do I set that with docker-compose?

**Comment by christronyxyocum** [comment]
You can't use wget for Docker images.

**Comment by jds11111** [comment]
You were essentially correct about network, but it was not really from my end. The repo blocks me because I am on a VPN.

I turn off the VPN, but now it complains about my using an alias for my network:
```
$ docker-compose pull && docker-compose up -d
Pulling organizr ... done
Recreating organizr ... error

ERROR: for organizr  network-scoped alias is supported only for containers in user defined networks

ERROR: for organizr  network-scoped alias is supported only for containers in user defined networks
ERROR: Encountered errors while bringing up the project.
```

I don't understand, because I created the network to connect a bunch of my containers. Maybe all the network containers need to all be created by docker-compose at the same time? Anyway, if I remove all the network bits, it seems to compose the container ok.  However, the web server tells me:

Organizr DB is not writable!!! Please fix...

I try:
`sudo chown -R www-data:www-data /var/www`

Or, to my login name, but it does not fix it.

**Comment by Roxedus** [comment]
The "repo" doesnt block anyone, that would be DockerHub, please create a new issue for your current issue, as that is actually a bug.

**Comment by jds11111** [comment]
OK, thanks.
