### ISSUE TITLE
Fresh install and database is not writable

### ISSUE THREAD

**Issue by jds11111** [Organizr/docker-organizr#8]
After my docker-compose install on linux, I get an error when I go to the web server:

Organizr DB is not writable!!! Please fix...

I try:
sudo chown -R www-data:www-data

Or, to my login name for the www directory in my configs, but it does not fix it.

**Comment by causefx** [comment]
what are the permission on the actual db folder?

**Comment by jds11111** [comment]
I have only one user on that machine, which is the owner of all the directories for all the libraries and configurations.

**Comment by causefx** [comment]
can you do an `ls -lah` on the db folder?

**Comment by jds11111** [comment]
```
~/configs/organizr/config/www/db$ ls -lah
total 8.0K
drwxrw---- 2 jds11111 jds11111 4.0K Jan 23  2020 .
drwxrwxr-x 4 jds11111jds11111 4.0K Oct 29 10:39 ..
```

**Comment by causefx** [comment]
That's odd there isn't even a Database in there.  

Couple of things:

What user is the container running as?

You can temporarily set that directory up as 777 to test then change it back...

Did you complete the setup wizard? 

Try deleting the api/config/config.php file and going through the setup again.  But this time hit the test path button on db folder.

**Comment by jds11111** [comment]
Yeah, odd.  There is organizr.db in ~/configs/organizr/config/www/organizr.  I make jds11111 an agent of docker:
`sudo usermod -a -G docker $USER`
I completed the wizard a couple of years ago, but haven't seen it with this install.
I did a chmod -R 777 on the organizr/config directory, but nothing changed.

I don't know what the "test path button" is, but deleting that file (which seems to be in a strange place) did give me the wizard. 

I want to be a little cautious here not to destroy my carefully constructed setup of Organizr.  I have backups of the configs, but...
So, I am hesitant to go through the wizard.

**Comment by jds11111** [comment]
I had an install for some time.  Then problems started with the migration to v2.1.  It sent me to a site that gave a docker-compose.yml sample, highlighting the changes.  Since I had the config files saved and backed up, I used autocompose.py to generate a docker-compose.yml for my original setup, deleted the old container, edited the docker-compose.yml with the new version, and tried to compose the new container.  That is when I ran into issues with the setup.  It is a new container, but trying to use the old config.

There is no config.php file there---perhaps because I did not go through the wizard?  There is a default.php, but no dbLocation in it.
If I look at the old config.php (that I renamed config.php.backup3), it has the line:
'dbLocation' => '/config/www/Dashboard/',
but inside the directory ~/configs/organizr/config/www, there is no Dashboard.
I can find no such directory.

**Comment by causefx** [comment]
There should be a config.php somewhere as that is the only way to get the error you are getting.  Either way, it seems you may have been using a different image and just now switched to organizr/organizr.  Can you paste your container setup - if you arent using docker-compose, what are you using? Portainer?

**Comment by jds11111** [comment]
I set it up by cli:

docker create --name=organizr \
--name=organizr \
  --restart always \
-v /home/jds11111/configs/organizr/config:/config \
-e PGID=1000 -e PUID=1000 \
-p 80:80 \
organizrtools/organizr-v2

**Comment by causefx** [comment]
delete that one and create it with organizr/organizr

**Comment by jds11111** [comment]
I already deleted that one---that is the one that was working for a couple of years. The current one with the problems was created by docker-compose:

services:
  organizr:
    container_name: organizr
    entrypoint:
      - /init
    environment:
      - fpm=true
      - branch=v2-master
      - PGID=1000
      - PUID=1000
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - HOME=/root
      - TERM=xterm
    hostname: organizr
    image: organizr/organizr
    ipc: private
    logging:
      driver: json-file
      options: {}
    mac_address: 02:42:ac:11:00:04
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - /home/jds11111/configs/organizr/config:/config
version: "3"
networks:
  bridge:
    external: true
  htpc_network:
    external: true

**Comment by causefx** [comment]
i'll be free a little later on today and will be able to help faster on discord.

**Comment by jds11111** [comment]
discord never lets me log in :(

**Comment by jds11111** [comment]
@causefx ,  thanks for your help.  I gave up on recovering the other setup.  I took a risk, and went through the wizard (that I only got because of you), then copied over my old *.db file to the new one. That gave me all the old tabs back, which were most of the work.  I had to re-do the homepage, but that was not so bad.  Then I made a backup for safe keeping.  Everything looks great. Thanks again.

**Comment by causefx** [comment]
Sweet!!!  You can also make a zip backup inside organizr too now.

**Comment by jds11111** [comment]
Yeah, I saw that and utilized it immediately after reconstructing my setup. Very useful. I also have all the config files copied over daily to my RAID for safekeeping.
